apiVersion: apps/v1                 # deployment
kind: Deployment
metadata:
  name: blog-deploy
  namespace: aws9b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog-ctn
          image: hub.aws9.pri/blog/blog:3.0
---
apiVersion: v1                     # service
kind: Service
metadata:
  name: blog-svc
  namespace: aws9b
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1  # ingress
kind: Ingress
metadata:
  name: blog-ingress
  namespace: aws9b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: www.aws9.pri
    http:
      paths:
        - path: /blog
          pathType: Prefix
          backend:
            service:
              name: blog-svc
              port:
                number: 80
