apiVersion: apps/v1                 # deployment
kind: Deployment
metadata:
  name: blog-deploy
  namespace: aws9b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: blog-ctn
          image: hub.aws9.pri/blog/blog:9.4
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: aws9b
  labels:
    app.kubernetes.io/instance: aws9toy
spec:
  type: ClusterIP
  selector:
    app: blog
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
---
apiVersion: networking.k8s.io/v1  # ingress
kind: Ingress
metadata:
  name: aws9b-svc-blog
  namespace: aws9b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: www.aws9.pri
    http:
      paths:
        - path: /blog
          pathType: Prefix
          backend:
            service:
              name: aws9b-svc-blog
              port:
                number: 80
