apiVersion: apps/v1                 # deployment
kind: Deployment
metadata:
  name: shop-deploy
  namespace: aws9b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop-ctn
          image: hub.aws9.pri/shop:latest
---
apiVersion: v1                     # service
kind: Service
metadata:
  name: shop-svc
  namespace: aws9b
spec:
  selector:
    app: shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1  # ingress
kind: Ingress
metadata:
  name: shop-ingress
  namespace: aws9b
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
  - host: www.aws9.pri
    http:
      paths:
        - path: /shop
          pathType: Prefix
          backend:
            service:
              name: shop-svc
              port:
                number: 80
