apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ghzx55/aws9b-repo.git
    targetRevision: main
    path: blog/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: aws9b
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
